import React, { useState } from 'react';
import { Users, Route, ShieldCheck, Leaf, Zap, ArrowRight, BarChart3, Wallet, Plus, X } from 'lucide-react';
import RouteMap from './RouteMap';
import { Badge, Empty, Stat, Timeline, BookingForm, money } from './UI';
import { normalizeDispatch } from '../apiAdapter';
export default function Admin(p) {
  const { tab, trip, queue, form, setForm, nodes, book, busy, dispatch, rejection, testRejection, benchmark, runBenchmark, mapProps, simulation, overlay, setOverlay } = p;
  const s = trip?.summary;
  return <>
    <div className="stats"><Stat label="Queued requests" value={queue.length} icon={Users} detail="Server-owned booking queue"/><Stat label="Vehicle distance saved" value={s ? `${s.distanceSavedKm} km` : '—'} icon={Route} detail={s ? `${s.distanceSavedPercent}% vs separate rides` : 'Available after dispatch'}/><Stat label="Shared route fare" value={money(s?.totalFareCollected)} icon={Wallet} detail="Budget-balanced fare allocation"/><Stat label="Detour protection" value="≤ 15%" icon={ShieldCheck} detail="Booking maximum"/></div>
    {tab === 'dispatch' && <div className="dispatch-grid"><section className="card"><div className="section-heading"><div><h2>Book a commuter</h2><p>Add a real request to the next batch.</p></div><Badge tone="cyan">Pune → Mumbai</Badge></div><BookingForm {...{form,setForm,nodes}} onSubmit={book} busy={!!busy}/></section><section className="card queue-card"><div className="section-heading"><div><h2>The next shared journey</h2><p>Manual dispatch · four seats per batch</p></div><Badge tone="green">{queue.length} waiting</Badge></div>{queue.length ? <div className="queue-list">{queue.map((r,i) => <div className="queue-rider" key={r.request_id}><span className={`avatar color-${i%3}`}>{r.passenger_name[0]}</span><div><strong>{r.passenger_name}</strong><p>{r.origin_name} → {r.destination_name}</p><small>{r.seats_requested} seat(s) · {r.max_detour_percent}% detour cap</small></div><Badge>Queued</Badge></div>)}</div> : <Empty title="Room for your next riders">Add a commuter or load the Golden Corridor demo.</Empty>}<div className="queue-footer"><p><ShieldCheck size={16}/> Fares and route appear only after successful dispatch.</p><button className="primary wide" disabled={!!busy || !queue.length} onClick={dispatch}><Zap size={17}/>{busy === 'dispatch' ? 'Optimizing…' : 'Dispatch batch'}<ArrowRight size={17}/></button></div></section></div>}
    {tab === 'map' && <section className="card map-card"><div className="section-heading"><div><h2>Every stop, in the right order.</h2><p>{trip ? 'Backend-optimized corridor route' : 'Corridor preview · dispatch a batch for results'}</p></div><button className="secondary" onClick={() => setOverlay(!overlay)}>{overlay ? 'Hide' : 'Show'} Vikram detour</button></div><div className="admin-map"><RouteMap {...mapProps}/></div>{simulation}{trip && <Timeline trip={trip}/>}</section>}
    {tab === 'shield' && <><div className="feature-banner"><ShieldCheck size={36}/><div><div className="eyebrow">CONVENIENCE SHIELD</div><h2>Your riders’ time comes first.</h2><p>Compare direct travel time with the actual modelled time in the shared cab.</p></div><strong>15<span>% maximum</span></strong></div>{trip ? <div className="rider-grid">{trip.commuters.map(r => <section className="card shield-card" key={r.id}><div className="section-heading"><h2>{r.name}</h2><Badge tone={r.detourPercent <= 15 ? 'green' : 'red'}>{r.detourPercent <= 15 ? 'Accepted' : 'Rejected'}</Badge></div><p>{r.origin} → {r.destination}</p><div className="detour-big">{r.detourPercent}<span>% detour</span></div><div className="fare-line"><span>Direct travel</span><b>{r.directTimeMin} min</b></div><div className="fare-line"><span>Shared travel</span><b>{r.actualTimeMin} min</b></div><div className="fare-line"><span>Extra travel</span><b>{r.detourMin.toFixed(1)} min</b></div><progress max="15" value={r.detourPercent} aria-label={`${r.name} detour against 15 percent cap`}/><small>0% <span className="right">15% limit</span></small></section>)}</div> : <Empty/>}<Rejection {...{rejection,testRejection,busy}}/></>}
    {tab === 'fairness' && <><div className="feature-banner"><Wallet size={36}/><div><div className="eyebrow">FAIRNESS LAB</div><h2>Different journeys. A fair share.</h2><p>Shapley allocation reflects each rider’s average marginal route contribution.</p></div><strong>{s ? s.platformDeficitPaise : '—'}<span>paise deficit</span></strong></div>{trip ? <><section className="card"><div className="section-heading"><div><h2>Follow the fare</h2><p>Compare the same route under three allocation methods.</p></div><Badge tone="green">Calculated by backend</Badge></div><div className="table-scroll"><table><thead><tr>{['Passenger','Solo estimate','Equal split','Distance split','Shapley fare','Savings'].map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{trip.commuters.map(r => <tr key={r.id}><td><b>{r.name}</b><small>{r.directDistKm} km direct</small></td><td>{money(r.soloFare)}</td><td>{money(r.equalSplitFare)}</td><td>{money(r.distanceSplitFare)}</td><td className="highlight">{money(r.shapleyFare)}</td><td className="green-text">{money(r.savingsAmount)}<small>{r.savingsPercent}%</small></td></tr>)}</tbody><tfoot><tr><td>Total shared fare</td><td colSpan="3"/><td className="highlight">{money(s.totalFareCollected)}</td><td>{money(trip.commuters.reduce((n,r) => n+r.savingsAmount,0))}</td></tr></tfoot></table></div></section><div className="two-col"><section className="card"><h2>Fare distribution</h2><p>Each bar is a share of the complete route fare.</p><div className="fare-bars">{trip.commuters.map((r,i) => <div key={r.id}><div><strong>{r.name}</strong><span>{money(r.shapleyFare)}</span></div><div className="bar-track"><span className={`bar color-${i%3}`} style={{width:`${s.totalFareCollected ? r.shapleyFare / s.totalFareCollected * 100 : 0}%`}}/></div></div>)}</div></section><section className="card"><h2>Why this price?</h2>{trip.commuters.map(r => <details key={r.id}><summary>{r.name} · {money(r.shapleyFare)}</summary><p>{r.shapleyExplanation}</p></details>)}</section></div></> : <Empty/>}</>}
    {tab === 'sandbox' && <><Rejection {...{rejection,testRejection,busy}}/><Sandbox {...p}/></>}
    {tab === 'benchmark' && <section className="card"><div className="section-heading"><div><div className="eyebrow">ENGINE SCORECARD</div><h2>Less distance. More possibility.</h2><p>The existing endpoint returns a fixed 100-commuter benchmark fixture; it does not run a new simulation.</p></div><button className="primary" disabled={!!busy} onClick={runBenchmark}><BarChart3 size={17}/>{busy === 'benchmark' ? 'Loading…' : 'Load benchmark'}</button></div>{benchmark ? <><Badge>Backend fixture · not a measured live run</Badge><div className="benchmark-grid"><Stat label="Commuters" value={benchmark.total_commuters_simulated} icon={Users}/><Stat label="Distance reduction" value={`${benchmark.distance_reduction_pct}%`} icon={Route}/><Stat label="P95 detour" value={`${benchmark.p95_detour_pct}%`} icon={ShieldCheck}/><Stat label="CO₂ reduction" value={`${benchmark.co2_reduction_kg} kg`} icon={Leaf}/><Stat label="Driver revenue increase" value={`${benchmark.driver_revenue_boost_pct}%`} icon={Wallet}/><Stat label="Platform deficit" value={`${benchmark.platform_deficit_paise} paise`} icon={Wallet}/></div><div className="distance-comparison"><h3>Vehicle distance comparison</h3><div><span>Separate rides</span><b>{benchmark.unpooled_total_distance_km} km</b></div><progress max={benchmark.unpooled_total_distance_km} value={benchmark.unpooled_total_distance_km}/><div><span>Shared rides</span><b>{benchmark.optimized_pooled_distance_km} km</b></div><progress max={benchmark.unpooled_total_distance_km} value={benchmark.optimized_pooled_distance_km}/></div><p className="micro">{benchmark.total_batches_dispatched} batches · reported max detour {benchmark.max_detour_pct}% · reported solver latency {benchmark.avg_solver_latency_ms} ms. Occupancy, match rate and delay distributions are not supplied by this endpoint.</p></> : <Empty title="Explore the benchmark">Load the existing backend scorecard to inspect its reported figures.</Empty>}</section>}
  </>;
}
function Rejection({ rejection, testRejection, busy }) { return <section className="card rejection-card"><div className="section-heading"><div><Badge tone="amber">Vikram rejection demonstration</Badge><h2>A match should never cost your time.</h2><p>Fixed backend scenario · separate from the current dispatch.</p></div><button className="secondary" disabled={!!busy} onClick={testRejection}>Test Vikram insertion</button></div>{rejection && <><div className="rejection-result"><Badge tone={rejection.feasible ? 'green' : 'red'}>{rejection.feasible ? 'Accepted' : 'Pool match rejected'}</Badge><strong>{rejection.actual_detour_pct}% detour</strong><span>{rejection.violating_rider} · {rejection.detour_cap_pct}% cap</span></div><p>{rejection.violating_rider} would travel {rejection.priya_pooled_time_min} minutes instead of {rejection.priya_direct_time_min} minutes (+{rejection.detour_delay_minutes} minutes).</p><p className="micro">Backend scenario action: {rejection.action}. This is an illustrative fallback decision; no private cab booking is created.</p></>}</section>; }
function Sandbox({ trip, nodes, api, perform, busy }) {
  const [cap,setCap] = useState(15), [candidate,setCandidate] = useState({name:'',pickup:'Talegaon',dropoff:'Panvel'}), [include,setInclude] = useState(false), [result,setResult] = useState(null), [resultCap,setResultCap] = useState(null);
  function run() { perform('sandbox', async () => {
    setResult(null);
    const riders = trip.commuters.map(r => ({rider_id:r.name,pickup:r.origin,dropoff:r.destination}));
    // Use canonical node identifiers carried by the adapter, never approximate map labels.
    riders.forEach((r,i) => { r.pickup=trip.commuters[i].pickupNode; r.dropoff=trip.commuters[i].dropoffNode; });
    if (include) {
      if (!candidate.name.trim()) throw Error('Enter a candidate name.');
      if (riders.some(r => r.rider_id === candidate.name.trim())) throw Error('Use a unique candidate name.');
      if (trip.commuters.reduce((s,r) => s+r.seats,0) >= 4) throw Error('This batch already reserves all four seats.');
      riders.push({rider_id:candidate.name.trim(),pickup:candidate.pickup,dropoff:candidate.dropoff});
    }
    const raw = await api('/api/optimize-corridor', {riders,max_detour_pct:cap});
    setResultCap(cap); setResult(raw.is_feasible ? { trip:normalizeDispatch(raw), feasible:true } : {feasible:false,reason:raw.error || raw.reason || raw.message || 'No route satisfies this configuration.'});
  }); }
  return <section className="card"><div className="section-heading"><div><div className="eyebrow">WHAT-IF SANDBOX</div><h2>One change. See the impact.</h2><p>Recompute a copy of the dispatched route. The queue and active trip stay unchanged.</p></div></div>{!trip ? <Empty title="Dispatch a route first">The simulator uses your current passengers as its starting point.</Empty> : <><div className="two-col"><div><label>Requested detour tolerance <b className="right">{cap}%</b><input aria-label="Sandbox detour tolerance" type="range" min="1" max="25" value={cap} onChange={e => { setCap(+e.target.value); setResult(null); }}/></label><p className="micro">Sandbox only: tolerances above 15% explore a relaxed policy. Passenger booking and batch dispatch remain capped at 15%.</p><label className="checkbox"><input type="checkbox" checked={include} onChange={e => { setInclude(e.target.checked); setResult(null); }}/> Add one candidate request</label>{include && <div className="candidate-fields"><label>Candidate name<input value={candidate.name} onChange={e => {setCandidate({...candidate,name:e.target.value}); setResult(null);}}/></label>{['pickup','dropoff'].map(k => <label key={k}>{k}<select value={candidate[k]} onChange={e => {setCandidate({...candidate,[k]:e.target.value}); setResult(null);}}>{nodes.map(n => <option key={n.name}>{n.name}</option>)}</select></label>)}</div>}<button className="primary" disabled={!!busy} onClick={run}><Zap size={17}/>{busy === 'sandbox' ? 'Evaluating…' : 'Evaluate scenario'}</button></div><div>{result ? <><Badge tone={result.feasible ? 'green' : 'red'}>{result.feasible ? 'Route accepted' : 'Route rejected'}</Badge><p>Requested cap {resultCap}% · evaluation cap {resultCap}%</p>{result.feasible ? <><div className="table-scroll"><table><thead><tr><th>Passenger</th><th>Shared time</th><th>Detour</th><th>Fare</th></tr></thead><tbody>{result.trip.commuters.map(r => <tr key={r.id}><td>{r.name}</td><td>{r.actualTimeMin} min</td><td>{r.detourPercent}%</td><td>{money(r.shapleyFare)}</td></tr>)}</tbody></table></div><p className="micro">The solver found a route satisfying pickup-before-drop-off and detour limits. This is a model evaluation, not a new booking.</p></> : <p>{result.reason}</p>}</> : <Empty title="Explore a different route">Adjust tolerance or add a candidate, then evaluate with the Python engine.</Empty>}</div></div></>}</section>;
}
