import React from 'react';
import { ArrowRight, Car, Leaf, ShieldCheck } from 'lucide-react';
export const money = n => n == null ? '—' : new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 2 }).format(n);
export function Badge({ children, tone = '' }) { return <span className={`badge ${tone}`}>{children}</span>; }
export function Empty({ title = 'Your next journey starts here', children }) { return <div className="empty"><span className="empty-icon"><Car size={30}/></span><h3>{title}</h3><p>{children || 'Book a ride or dispatch the Golden Corridor demo to see results from the engine.'}</p></div>; }
export function Stat({ label, value, detail, icon: Icon = Leaf }) { return <div className="stat"><Icon size={19}/><span>{label}</span><strong>{value}</strong>{detail && <small>{detail}</small>}</div>; }
export function Timeline({ trip, step = -1 }) { return <ol className="timeline">{trip.stops.map((s, i) => <li key={i} className={i === step ? 'current' : ''}><span className={`timeline-dot ${s.type === 'DROPOFF' ? 'drop' : ''}`}>{i + 1}</span><div><small>{s.type === 'PICKUP' ? 'PICK UP' : s.type === 'DROPOFF' ? 'DROP OFF' : 'DROP OFF / PICK UP'}</small><strong>{s.rider}</strong><p>{s.node}</p></div><span className="stop-km">{s.km} km</span></li>)}</ol>; }
export function Fare({ rider }) { return <div className="fare-detail"><div className="fare-top"><span>Your shared fare<strong>{money(rider.shapleyFare)}</strong></span><Badge tone="green">{rider.savingsPercent}% saved</Badge></div><div className="fare-line"><span>Solo fare estimate</span><del>{money(rider.soloFare)}</del></div><div className="fare-line"><span>You save</span><b>{money(rider.savingsAmount)}</b></div><p>Fairly divided using your contribution to the shared route.</p><details><summary>Why this price?</summary><p>{rider.shapleyExplanation}</p></details></div>; }
export function BookingForm({ form, setForm, nodes, onSubmit, busy }) {
  const update = (key, val) => setForm(f => ({ ...f, [key]: val }));
  return <form onSubmit={onSubmit} className="booking-form"><div className="location-fields"><label><span className="location-dot"/>Pickup<select aria-label="Pickup" value={form.origin} onChange={e => update('origin', e.target.value)}>{nodes.filter(n => n.is_mainline).map(n => <option key={n.name}>{n.name}</option>)}</select></label><label><span className="location-dot destination"/>Destination<select aria-label="Destination" value={form.destination} onChange={e => update('destination', e.target.value)}>{nodes.filter(n => n.is_mainline).map(n => <option key={n.name}>{n.name}</option>)}</select></label></div><div className="form-row"><label>Your name<input required maxLength={70} placeholder="e.g. Sameer" value={form.name} onChange={e => update('name', e.target.value)}/></label><label>Seats<select value={form.seats} onChange={e => update('seats', +e.target.value)}>{[1,2,3,4].map(n => <option value={n} key={n}>{n} {n === 1 ? 'seat' : 'seats'}</option>)}</select></label></div><label>Phone <span className="optional">optional</span><input type="tel" placeholder="+91" value={form.phone} onChange={e => update('phone', e.target.value)}/></label><div className="ride-choice"><Car size={29}/><span><strong>SmartPool</strong><small>Shared route. Fair fare.</small></span><Badge tone="blue">Shared</Badge></div><div className="protection"><ShieldCheck size={17}/><span>Up to {form.cap}% extra travel time</span></div><details className="preferences"><summary>Ride preferences</summary><label>Maximum detour: {form.cap}%<input aria-label="Maximum booking detour" type="range" min="0" max="15" value={form.cap} onChange={e => update('cap', +e.target.value)}/></label><p>Private rides are not available through this demo API.</p></details><button className="primary wide" disabled={busy || !nodes.length}>{busy ? 'Adding your request…' : 'Find a shared ride'}<ArrowRight size={18}/></button><p className="micro center">Fare calculated after matching · No payment required</p></form>;
}
